model_name_or_path: /data/hfc/checkpoints/gemma-3-4b-it
# adapter_name_or_path: /data/hfc/RoleRAG/saves/刘星_only_dpo/llama3_8b_dpo_lora/TorchTrainer_9a143_00000_0_2025-04-13_13-03-13/checkpoint_000002/checkpoint
# adapter_name_or_path: /data/hfc/RoleRAG/saves/刘星_cot_800/llama3_8b_sft_lora/TorchTrainer_8d771_00000_0_2025-04-17_18-20-14/checkpoint_000003/checkpoint
template: gemma3
infer_backend: huggingface  # choices: [huggingface, vllm]
trust_remote_code: true
