model_name_or_path: /data/hfc/checkpoints/GLM-4-9B-0414
adapter_name_or_path: /data/hfc/RoleRAG/saves/刘星_glm4_style/glm4_8b_sft_lora/TorchTrainer_436ee_00000_0_2025-04-29_10-32-58/checkpoint_000001/checkpoint
# adapter_name_or_path: /data/hfc/RoleRAG/saves/刘星_style/llama3_8b_sft_lora/TorchTrainer_9fdfa_00000_0_2025-04-16_18-36-15/checkpoint_000000/checkpoint
template: glm4
infer_backend: huggingface  # choices: [huggingface, vllm]
trust_remote_code: true
