### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: /data/hfc/checkpoints/Llama-3.1-8B-Instruct
adapter_name_or_path: /data/hfc/RoleRAG/saves/刘星_cot/llama3_8b_sft_lora/TorchTrainer_97609_00000_0_2025-04-16_16-34-20/checkpoint_000000/checkpoint
template: llama3
trust_remote_code: true

### export
export_dir: output/刘星_style
export_size: 5
export_device: cpu
export_legacy_format: false
